name: Update plugin count

on:
  #pull_request:
  push:
    branches:
    - main
    paths:
    - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Update README
      run: ruby .github/scripts/parse.rb
    - name: Commit and push if README changed
      run: |-
        git diff
        git config user.name "Awesome YOURLS Robot"
        git config user.email "yourls@users.noreply.github.com"
        git add -A
        git commit -m "Update plugin count" || exit 0
        git push      
